# needed a patch because manifests.yaml gets overwritten by kustomize
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
